language: c

env:
  global:
    - HDF_ROOT="/usr"
  matrix: 
      - FC=gfortran-5 CC=gcc-5          

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-5
      - gfortran-5
      - libhdf5-openmpi-dev

before_script:
        - cmake . -DWITH_HDF5=0 -DBUILD_SHARED_LIBS=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr

script: make
        
